server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: d3c0d3r
  jpa:
    hibernate:
      ddl-auto: update # reflects directly in bank when there's changes
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.nom-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
